### ISSUE TITLE
OPC enrichment values may be artificially increased by microglial contamination

### ISSUE THREAD

**Issue by dzoll** [dhimmel/opcendo#3]
Daniel,

I did not take into account the disclaimer in the Barres RNAseq database that states OPC contain 5% contamination by microglia.  We need to add an additional filter to the code that identifies genes enriched in OPCs while avoiding these false positives.

So the criteria needs to be something like:
 ['Oligodendrocyte Precursor Cell'] / ['Myelinating Oligodendrocytes'] > fc_cutoff AND ['Oligodendrocyte Precursor Cell'] > 0.05*['Microglia'] for a given gene.

I found at least one false positive in my results that may be a useful example: Icam1 (http://web.stanford.edu/group/barres_lab/cgi-bin/igv_cgi_2.py?lname=icam1).  The high enrichment in microglia likely provides the small enrichment in OPCs.

Thanks,

Dan

**Comment by dhimmel** [comment]
So in short, we're filtering for genes enriched in `Oligodendrocyte Precursor Cell`s compared to `Myelinating Oligodendrocytes`. However, `Oligodendrocyte Precursor Cell` is contaminated with 5% microglia.

I see two options:
1. Computing a corrected `Oligodendrocyte Precursor Cell` which removes the contribution of the 5% `Microglia`.
2. Adding an extra filter when selecting candidate genes, such as `Oligodendrocyte Precursor Cell > 0.05 * Microglia` (@dzoll's suggestion [above](#issue-141752227)).

Solution 1 corrects the OPC expression for all genes, but is more complicated than 2.

For reference, I believe the disclaimer @dzoll references appears when you search for a gene (for example [`Icam1`](http://web.stanford.edu/group/barres_lab/cgi-bin/igv_cgi_2.py?lname=icam1)) and states:

> OPCs have 5% microglial contamination

**Comment by dhimmel** [comment]
Steven Sloan from the Brain RNA-Seq team prefers Solution 2 from [above](#issuecomment-198430949) writing:

> I'd agree with solution 2. Just add a second requirement that any OPC enriched gene must not also be highly expressed in microglia.

@dzoll, should we implement "not being highly expressed in microglia" as a strict FPKM cutoff in `Microglia` or as an FPKM comparison between `Oligodendrocyte Precursor Cell` and `Microglia`?
