### ISSUE TITLE
Specifying which gene is the candidate for which cell type

### ISSUE THREAD

**Issue by dhimmel** [dhimmel/opcendo#5]
While working on #4, I realized the codebase is getting a bit complicated. Now that I have a better idea of the project goals, I think it makes sense to specify for each interaction which gene is the OPC-receptor candidate and which gene is the endothelial-receptor candidate. 

The `interactions` table columns would change from:
- `name_a` to `opc_gene`
- `name_b` to `endo_gene`
- `opc_l2fc_a`  to `opc_l2fc`
- remove `endo_l2fc_a`
- `dac_l2fc_a` to `opc_dac_l2fc`
- remove `opc_l2fc_b`
- `endo_l2fc_b` to `endo_l2fc`
- `dac_l2fc_b` to `endo_dac_l2fc`

From a network perspective, this is equivalent to adding directionality to edges. Edges will go from OPC candidate gene to endothelial cell candidate gene. Accordingly, we may now have two rows with the same two genes, just with their directionality switched.

@dzoll does this change make sense to you? Am I correct to assume that you don't care about OPC fold change for the endothelial cell candidate and vice versa. However, you do care about DAC fold change for both candidates?

**Comment by dzoll** [comment]
This all makes sense @dhimmel.  But it is important to keep in mind that one gene may be expressed in both cell types.  So we do care about OPC fold change for the endothelial cell candidates.  However, as long as the genes with expression in both cells show up twice (as OPC candidate and then again as an endothelial candidate) this will not be a concern.
